### ISSUE TITLE
tmux-tokyo-night theme failed to install on tmux 

### ISSUE THREAD

**Issue by ciscohack** [fabioluciano/tmux-tokyo-night#10]
Hi,

I tried to download the Tokyo theme in my Tmux but it keeps failing on installation. can you please help fixing this problem

<img width="1217" alt="image" src="https://github.com/fabioluciano/tmux-tokyo-night/assets/11479557/ecd01c81-a466-48fa-87b4-6c9e4040980f">

**Comment by ciscohack** [comment]
I think issue is with Tmux script 

#!/usr/bin/env bash      <<<  **I am running macOS 14 on M2 mac which has default zsh  please help to fix the issue**

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"${CURRENT_DIR}/src/theme.sh"

**Comment by ciscohack** [comment]
Any help plsease

**Comment by fabioluciano** [comment]
Hi friend! how are you :)

How is your tmux.conf file?

**Comment by ciscohack** [comment]
@fabioluciano Hey I am very much fine my friend thanks for your response... I was waiting for your msg. So I am using Oh-my-tmux and it's config ..it was working on the macOS 13 intel model but recently I changed my laptop to M2 and macOs 14 and noticed this stopped working and giving me an error which I mentioned.. Any specific config you looking for then let me know

**Comment by Davey-Hughes** [comment]
Hey I ran into this issue too- the version of bash that ships with MacOS is very old- if you install a newer version of bash such as through homebrew, the /usr/bin/env bash shebang should pick it up and run the script. If the env bash doesn't pick it up, you can figure out where your package manager installed bash with `where bash` in zsh, and it should give you something like `/opt/homebrew/bin/bash` and you can change the script to point to that directly.

**Comment by ciscohack** [comment]
@Davey-Hughes Thanks. It's strange that macOS 14 is coming up with an old bash .. this tmux theme was working fine on Ventura so Sonoma must have a higher or equal version right? so ideally it should work

**Comment by joelebeau** [comment]
> Hey I ran into this issue too- the version of bash that ships with MacOS is very old- if you install a newer version of bash such as through homebrew, the /usr/bin/env bash shebang should pick it up and run the script. If the env bash doesn't pick it up, you can figure out where your package manager installed bash with `where bash` in zsh, and it should give you something like `/opt/homebrew/bin/bash` and you can change the script to point to that directly.

Installed newer bash via Homebrew and it worked like a charm. Thanks. Before upgrading I only had the system's bash which was 3.3 and didn't support the array syntax in the palletes.

**Comment by heero7** [comment]
> Hey I ran into this issue too- the version of bash that ships with MacOS is very old- if you install a newer version of bash such as through homebrew, the /usr/bin/env bash shebang should pick it up and run the script. If the env bash doesn't pick it up, you can figure out where your package manager installed bash with `where bash` in zsh, and it should give you something like `/opt/homebrew/bin/bash` and you can change the script to point to that directly.

Just wanted to say this is something I had to do as well. Simply just ran `brew install bash`. Then ran `where bash` and it showed me

```
/opt/homebrew/bin/bash
/bin/bash
/opt/homebrew/bin/bash
```
Then it started working!
