### ISSUE TITLE
Weather status bar not showing in MacOS

### ISSUE THREAD

**Issue by chetra-seng** [fabioluciano/tmux-tokyo-night#33]
I really like this theme and I tried in both my personal machine (MacOS) and work machine (WSL). After the installation, I immediately noticed the different with weather status bar. Based on the default configuration, the weather should appear in MacOS as well.

**Comment by fabioluciano** [comment]
Can you tell if there is any error?

**Comment by chetra-seng** [comment]
Hi @fabioluciano, there's no error actually. I just could see the weather status bar on my MacBook. However, I can see it on WSL with the same configuration

**Comment by fabioluciano** [comment]
This id strange... The weather is showing in my MacOs heheh

Let me investigate what could be happening.

**Comment by cameronr** [comment]
@chetra-seng do you have `jq` installed? if not, `brew install jq` and maybe that will fix it

**Comment by chetra-seng** [comment]
@cameronr Yes, I have `jq` installed long ago. I've checked the source code.
```sh
function load_plugin() {
	if ! command -v jq &>/dev/null; then
		exit 1
	fi

	LOCATION=$(curl -s http://ip-api.com/json | jq -r '"\(.city), \(.country)"' 2>/dev/null)
	WEATHER=$(curl -sL wttr.in/${LOCATION// /%20}\?format="${plugin_weather_format_string}" 2>/dev/null)

	echo "${WEATHER}"
}
```
I'll try running this command locally to see what went wrong.
