### ISSUE TITLE
'/opt/homebrew/opt/tpm/share/tpm/tpm' returned 1 on MacOS

### ISSUE THREAD

**Issue by brandon-kyle-bailey** [fabioluciano/tmux-tokyo-night#46]
System info:
- MacOS Sonoma v14.6.1
- iTerm2 v3.5.4

Steps to reproduce:
- install tmux 3.4 via homebrew: `brew install tmux`
- install tpm via homebrew: `brew install tpm`
- create `tmux.conf` file in `~/.config/tmux/` with the following contents:
```bash
# Set prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'fabioluciano/tmux-tokyo-night'
### Tokyo Night Theme configuration
# set -g @theme_left_separator ''
# set -g @theme_right_separator ''
# set -g @theme_plugins 'homebrew,datetime,weather,yay'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
```
- start tmux session
- prefix-I to install plugins
- see error

Hey devs! loving this theme and new to tmux. i have this setup on my personal ubuntu machine, but trying to set it up on my work machine i encounter the following error. Have not have any success in troubleshooting via tpm directly. Any suggestions/support would be greatly appreciated! 

TIA

**Comment by harupong** [comment]
see #1 
it worked for me.

**Comment by brandon-kyle-bailey** [comment]
@harupong will give that a go!

**Comment by brandon-kyle-bailey** [comment]
@harupong that did the trick. Thanks!
