### ISSUE TITLE
Loading tmux.conf after adding set -g @plugin 'fabioluciano/tmux-tokyo-night fails

### ISSUE THREAD

**Issue by blame-git** [fabioluciano/tmux-tokyo-night#5]
Adding the line `set -g @plugin 'fabioluciano/tmux-tokyo-night'`
to my tmux config located at `~/.config/tmux/tmux.conf` always results in:

```
% tmux source ~/.config/tmux/tmux.conf
'~/.tmux/plugins/tpm/tpm' returned 1
```

os: macOS Ventura
tmux: 3.3a

**Comment by KalleChen** [comment]
Got the same issue.

In my case, my bash version is 3 and it seems that this plugin use new way to declare an array with bash. Therefore, I would need to upgrade my bash version to 4 or higher.

Hope this works for you.

p.s. if you use homebrew, you can just use `brew install bash` to easily upgrade your bash version.

**Comment by patrickTumulty** [comment]
Same issue on Mac OS Monterey 12.6.8. Using `zsh` version `5.8.1`.

**Comment by KalleChen** [comment]
@patrickTumulty 

This plugin use you bash to run the shell script, `#!/usr/bin/env bash` with this shebang.
Therefore, whether you're using zsh doesn't matter, it depends on your bash. And as i said above, you need to have a 4 or higher version of bash to run this plugin.

Besides, i found a similar issue #1 , hope this works for you.

**Comment by patrickTumulty** [comment]
Didn't realize the bash version was still relevant even when using zsh. Thanks for the info. Will look into upgrading bash.
