### ISSUE TITLE
How do I set the location for a @theme_plugin_weather?

### ISSUE THREAD

**Issue by renanmartins1813** [fabioluciano/tmux-tokyo-night#54]
```
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_plugin_weather 'on'
set -g @theme_plugin_weather_location '-23.533773,  -46.625290'
```
my current tmux.conf setup but i'm not getting the correct weather for my location, sadly i didn't find what i'm missing on my own

**Comment by tastychicken** [comment]
I read up some on the weather plugin script and it doesn't look like it's accepting a `@theme_plugin_weather_location` parameter.

It looks like it is trying to automatically determine your location with the following line:
`LOCATION=$(curl -s http://ip-api.com/json | jq -r '"\(.city), \(.country)"' 2>/dev/null)`

What do you get if you just run?:
`curl -s http://ip-api.com/json`

Obviously don't post your location, but if that doesn't match with where you are at that could be the cause.

**Comment by renanmartins1813** [comment]
its returning the right city thou my country have more than one city with the same name

**Comment by tastychicken** [comment]
If it's the right city maybe check what else you get from the json response? Are the lat/lon values correct?

The script for weather is pretty simple so you could always have a look if you can tell why it's not giving you the right data:
https://github.com/fabioluciano/tmux-tokyo-night/blob/main/src/plugin/weather.sh

The script uses the https://wttr.in site for weather data.

**Comment by renanmartins1813** [comment]
Plot twist: google and my gnome extension are wrong

I bought a little thermal device and its reading is very close with the wttr.in, off only by more or less than 1 °C while the gnome extension and google are off by 4/5°C

Thank you very much for all the support
